// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vafsiazonfmthfrlmllh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZnNpYXpvbmZtdGhmcmxtbGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTk1MjEsImV4cCI6MjA3MjU3NTUyMX0.M6uXQgJzU-LMydwWz-McbKQ8b6Br0KKpNd8hrCfB1Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});